echo hello terminal
pwd
ls
cd freeCodeCamp
pwd
ls
cd folder-name
cd test
pwd
ls
cd ..
ls
more package.json
clear
ls
cd <folder_name>
cd node_modules
ls
-l
l
ls -l
cd has
ls
more README.md
ls
more LICENSE-MIT
clear
ls
cd src
pwd
ls
more
more filename
more index.js
..cd
cd ..
cd
cd ..
has
cd /workspace/project/freeCodeCamp/node_modules/has
has
cd ..
cd ../..
ls
clea
 clear
mkdir website
ls
cd website
ls
echo hello website
touch index.html
touch styles.css
ls
touch index.js
touch .gitignore
 ls
ls --help
ls -a
cd .
touch background.jpg
touch header.png
touch footer.jpeg
ls
touch roboto.font
touch lato.font
touch menlo.font in the terminal
ls
touch CodeAlly.svg
touch CodeRoad.svg
touch freeCodeCamp.svg
ls in the terminal
mkdir images
 ls
cp background.jpg images
cd images
ls
cd ..
ls
rm background.jpg
ls
cp header.png images
cp footer.jpeg images
cd images
ls
cd ..
ls
rm header.png
rm footer.jpeg
ls
 mv roboto.font roboto.woff
ls
mv lato.font lato.ttf
mv menlo.font menlo.otf
ls
mkdir fonts
ls
mv roboto.woff fonts
find
mv lato.ttf fonts
mv menlo.otf fonts
find
mkdir client
kdir client/src
mkdir client/src
mv index.html client/src
 find
 mv index.js client/src
mv styles.css client/src
find
find client
find --help
find -name index.html
find -name style.css
find -name style.css
cd /workspace/project/website
find -name style.css 
cd /workspace/project/website
find -name style.css
cd /workspace/project/website
find -name style.css
find -name styles.css
find -name src
find
cd client
mkdir assets
cd assets
mkdir images\
cd images
 touch background.jpg
cd ../../..
cd images
ls
mv header.png ..
ls
cd ..
ls
find -name images
mv header.png client/assets/images
find -name header.png
find -name footer.jpeg
mv images/footer.jpeg client/assets/images
 find
rmdir images
rm images/background.jpg
rmdir images
ls
mkdir client/assets/icons
mv CodeAlly.svg client/assets/icons
find
mv CodeRoad.svg client/assets/icons
mv freeCodeCamp.svg client/assets/icons
 find
mkdir client/assets/fonts
touch client/assets/fonts/roboto-bold.woff
touch client/assets/fonts/roboto-light.woff
find client/assets/fonts
touch client/assets/fonts/lato-bold.ttf
touch client/assets/fonts/lato-light.ttf
find
 rm --help
rm -r fonts
 ls
touch package.json
touch server.js
touch README.md
ls
echo Yay!
echo I finished the boilerplate!
echo one more thing...
echo I made this boilerplate >> README.md
more README.md
echo from the command line >> README.md
more README.md
echo for the freeCodeCamp bash lessons >> README.md
more README.md
cd ..
ls
mv website website-boilerplate
ls
cp --help
 cp -r website-boilerplate toms-website
 ls
find toms-website
find website-boilerplate
clear 
echo goodbye terminal
exit
